stages:
 - build

Ubuntu-Optional-Deps:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export CMAKE_EXTRA_TARGETS="install"
  - export BUILD_OPTIONALS_SUBPROJECTS=1
  - export CMAKE_EXTRA_ARGS=-DNEUROSCHEME_OPTIONALS_AS_REQUIRED=ON
  - export BUILD_GENERATOR="Ninja"
  - bash .gitlab-ci.sh
 tags:
  - ubuntu

Ubuntu-Subproject:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export BUILD_GENERATOR="Ninja";
  - bash .gitlab-ci.sh
 tags:
  - ubuntu

OSX-Optional-Deps:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - module load Qt-5.4
  - export BUILD_OPTIONALS_SUBPROJECTS=1
  - export CMAKE_EXTRA_ARGS="-DNEUROSCHEME_OPTIONALS_AS_REQUIRED=ON -DLibJpegTurbo_INCLUDE_DIR=/usr/local/opt/jpeg-turbo/include -DLibJpegTurbo_LIBRARY=/usr/local/opt/jpeg-turbo/lib/libturbojpeg.dylib"
  - export BUILD_GENERATOR="Ninja"
  - export CMAKE_OSX_ARCHITECTURES=x86_64
  - bash .gitlab-ci.sh
 tags:
  - osx

OSX-Subproject:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - module load Qt-5.4
  - export BUILD_GENERATOR="Ninja";
  - export CMAKE_OSX_ARCHITECTURES=x86_64
  - bash .gitlab-ci.sh
 tags:
  - osx

Win7-Subproject-vs14:
  stage: build
  script:
  - call %ENVFILESDIR%\Boost-1.64-vs14-x64.bat
  - call %ENVFILESDIR%\Qt-5.9-vs14.bat
  - call %ENVFILESDIR%\eigen-3.1.2-vs12-x64.bat
  - set BUILD_GENERATOR=Visual Studio 14 Win64
  - set GENERATOR_EXTRA_OPTIONS=
  - '"c:\Program Files (x86)\Git\bin\bash.exe" --login  .gitlab-ci.sh'
  - set PATH=%PATH%;"c:\Program Files (x86)\Git\bin"
  tags:
  - win7
  except:
  - tags
